### ISSUE TITLE
how i can add Facebook login api in this app 

### ISSUE THREAD

**Issue by saroar** [itzikbenh/Rails-React-Auth#2]
what i mean you create api for rails login now is it possible to add this app fb login api so i client can use our api

**Comment by itzikbenh** [comment]
First, thanks for watching my videos. 
Now, this is not the place to ask "how to" questions. This is a place to open issues. What you're asking is how to add a feature, this is not an issue in the code. 
Your question is too big for me to answer here.  You will probably want to use a plugin for that, something like https://github.com/magus/react-native-facebook-login for the react native side. For the rails side you can use this https://github.com/mkdynamic/omniauth-facebook.

You will have to do some reading and figure out how this is done. If you get stuck then just ask in a forum or so more specific questions. 

Good luck!
